version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
